# docker-compose.yml
version: "3.8"

services:
  api-proxy:
    image: node:18
    container_name: api_proxy
    working_dir: /app
    command: node index.js
    volumes:
      - .:/app
    networks:
      - web_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-http.entrypoints=http"
      - "traefik.http.routers.api-http.rule=Host(`api.hojjatsa.com`)"
      - "traefik.http.routers.api-http.middlewares=https-redirect@docker"
      - "traefik.http.routers.api-https.entrypoints=https"
      - "traefik.http.routers.api-https.rule=Host(`api.hojjatsa.com`)"
      - "traefik.http.routers.api-https.tls=true"
      - "traefik.http.routers.api-https.tls.certresolver=mycert"
      - "traefik.http.services.api-proxy.loadbalancer.server.port=3000"

networks:
  web_net:
    external: true
